### PR TITLE
Delete tag before making a release

### PR DESCRIPTION
**Pull request by Uranite**
So that the date and the associated commit is updated in the github release

### CODE REVIEW

**Comment by Uranite** [comment]
On second thought, let me try some other things

**Comment by Uranite** [comment]
Yeah, none of the thing that I thought of worked, other than this
This PR is ready to merge

**Comment by shssoichiro** [comment]
I'm a little confused as to what this is trying to solve, since I want to make sure this doesn't have any undesirable effects. Could you explain a bit further?

**Comment by Uranite** [comment]
It's a workaround to ensure that the date and commit of the latest GitHub release are updated. As you can see in the picture, the date and commit are currently outdated
librewolf_1473_2024-11-07-1730968311

**Review by shssoichiro — APPROVED** [review]

**Pull request merged**
