### PR TITLE
Correct ffmpeg example

### PR DESCRIPTION
**Pull request by anoop142**

### CODE REVIEW

**Review by shssoichiro — APPROVED** [review]
Thanks!

**Comment by dexeonify** [comment]
Maybe remove the extra space between the quotes as well since it’s no longer needed?

**Comment by shssoichiro** [comment]
P.S. We are aware of the failing CI, it is due to a change in SVT-AV1 and not related to this PR. We're working on getting it fixed.

**Comment by redzic** [comment]
Ooops, I did not mean to close this PR. I was trying to rebase it

**Comment by redzic** [comment]
Sorry @anoop142, somehow when I tried rebasing, it reset your branch to the current master causing the PR to automatically be closed (since there are no new commits). Can you add the commit to your fork again? I tried to fix it myself but I was getting a `[remote rejected]` error from git.

**Comment by anoop142** [comment]
okay

**Pull request closed without merging**
