### PR TITLE
Make --vmaf parameter work independently again

### PR DESCRIPTION
**Pull request by damster101**
Solves issue #824

### CODE REVIEW

**Comment by shssoichiro** [comment]
Needs a rustfmt please

**Comment by damster101** [comment]
> Needs a rustfmt please

Better now?

But someone really should run rustfmt on the entire project, I had to "fix" all those indentations to match the rest of the project...

**Comment by shssoichiro** [comment]
That's weird, it should already be correct for the rest of the project. The CI validates it on each MR.

**Comment by damster101** [comment]
> That's weird, it should already be correct for the rest of the project. The CI validates it on each MR.

It seems rustfmt behaves VERY differently when I run it on the whole context.rs file compared to just the isolated function. I did the latter and got a ton of changes everywhere, especially lots of two space indentations were increased in size to four spaces.
But, if I run rustfmt on the whole context.rs file, it seems to recognize that a different style is used and doesn't perform any of these changes.

Btw, I would have expected that this behavior could be influenced by the user for whole project files, but there doesn't seem to be an option for it...

**Comment by damster101** [comment]
So, it looks like the way to get modern Rust formatting for a large project is to omit all the lines starting with `use` at the beginning of the Rust project files when formatting them with rustfmt.

**Comment by damster101** [comment]
Once some part of the file is formatted in the modern default style, running rustfmt on the whole file will change everything to it.

**Review by shssoichiro — APPROVED** [review]

**Pull request merged**
