### PR TITLE
Add --output_ivf flag to remux VP9 and AV1 to ivf

### PR DESCRIPTION
**Pull request by redzic**
Adds `--output_ivf` flag which remuxes ivf files into a single ivf file. On some inputs there still seems to be an issue with the video length in the metadata which I tried to fix by using the sum of duration in the metadata of the individual clips, but in those cases the video still plays fine, and seeking works.

### CODE REVIEW

**Comment by master-of-zen** [comment]
@redzic Great) :medal_sports:

**Comment by redzic** [comment]
looks like `vspipe` is failing in CI

**Comment by master-of-zen** [comment]
:thinking:

**Comment by redzic** [comment]
ok so the problem is with lsmash, it's saying it can't construct the index

**Comment by redzic** [comment]
so issue is somewhere in rust implementation of `create_vs_file`, probably somewhere with resolving paths but I will have to check

**Comment by redzic** [comment]
@master-of-zen should be fixed now, issue was that it was using a relative path in the vapooursynth input file for the source

**Comment by master-of-zen** [comment]
@redzic :+1:

**Pull request merged**
