### PR TITLE
Update to ffmpeg 5.0

### PR DESCRIPTION
**Pull request by redzic**
- Also rename ffmpeg-next in Cargo.toml, and refer to our own ffmpeg module by `crate::ffmpeg`

### CODE REVIEW

**Comment by shssoichiro** [comment]
Tests do not seem to like that...

> Error: ffmpeg: failed to get pixel format for input video "tt_sif.y4m"

**Comment by shssoichiro** [comment]
Does the CI runner also need to be on ffmpeg 5? Could that potentially cause this issue?

**Comment by redzic** [comment]
Actually I can reproduce the CI failure locally as well... so I'm not sure exactly what's wrong. I'll try to debug the issue further.

**Comment by redzic** [comment]
It now runs fine for me locally (and `all-tests` seem to pass as well), but it looks like there's an issue with compiling on the docker container?

**Comment by master-of-zen** [comment]
Works now))

**Review by master-of-zen — APPROVED** [review]
Great job :)

**Comment by svenstaro** [comment]
@master-of-zen Could we get a new release containing this update? I'd like to build av1an against ffmpeg in Arch in order to prepare for the drop of ffmpeg4.4 and av1an is currently one of the blocking packages.

**Comment by shssoichiro** [comment]
It looks like we'll need new releases of rav1e, av-scenechange, vapoursynth-rs, and console, since we are still depending on git versions of those. I can push for a release on the first two. Not sure about the latter two.

**Pull request merged**
